// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY3Ipr2bBJAPnoOW7_xv1bCi1ytadgRtM',
    appId: '1:794341577602:web:d393da9b315c934eaab59b',
    messagingSenderId: '794341577602',
    projectId: 'fire-social-media-57741',
    authDomain: 'fire-social-media-57741.firebaseapp.com',
    storageBucket: 'fire-social-media-57741.firebasestorage.app',
    measurementId: 'G-PY7TTX60TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfkP2-0zGwlvnmNIX1BAZJvVRgbhYukyw',
    appId: '1:794341577602:android:d748dc17a6c58c9eaab59b',
    messagingSenderId: '794341577602',
    projectId: 'fire-social-media-57741',
    storageBucket: 'fire-social-media-57741.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpi9qy5XIXvhQqnlG73OoDRnUGBdgLzZA',
    appId: '1:794341577602:ios:a5ace450685b540baab59b',
    messagingSenderId: '794341577602',
    projectId: 'fire-social-media-57741',
    storageBucket: 'fire-social-media-57741.firebasestorage.app',
    iosBundleId: 'com.example.fireSocialMedia',
  );
}
